export type BusinessLocation = {
  id: number;
  business_id: number;
  location_id: string;
  name: string;
  landmark: string;
  country: string;
  state: string;
  city: string;
  zip_code: string;
  invoice_scheme_id: number | null;
  sale_invoice_scheme_id: number;
  invoice_layout_id: number | null;
  sale_invoice_layout_id: number | null;
  selling_price_group_id: number | null | any;
  print_receipt_on_invoice: number | null;
  receipt_printer_type: string;
  printer_id: number | null;
  mobile: string;
  alternate_number: string;
  email: string;
  website: string;
  featured_products: any;
  is_active: number | boolean;
  custom_field1: string | null;
  custom_field2: string | null;
  custom_field3: string | null;
  custom_field4: string | null;
  accounting_default_map: any;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  payment_methods: {
    name: string;
    label: string;
    account_id: number | null;
  }[];
};

export type Product = {
  id: number;
  name: string;
  business_id: number;
  type: string;
  secondary_unit_id: number | null;
  sub_unit_ids: number[] | null;
  enable_stock: number;
  alert_quantity: string;
  sku: string;
  barcode_type: string;
  expiry_period: number | null;
  expiry_period_type: string | null;
  expiry_date: string;
  enable_sr_no: number;
  weight: number | null;
  product_custom_field1: string;
  product_custom_field2: string;
  product_custom_field3: string;
  product_custom_field4: string;
  product_custom_field5: string;
  product_custom_field6: string;
  product_custom_field7: string;
  product_custom_field8: string;
  product_custom_field9: string;
  product_custom_field10: string;
  product_custom_field11: string;
  product_custom_field12: string;
  product_custom_field13: string;
  product_custom_field14: string;
  product_custom_field15: string;
  product_custom_field16: string;
  product_custom_field17: string;
  product_custom_field18: string;
  product_custom_field19: string;
  product_custom_field20: string;
  image: string;
  woocommerce_media_id: number | null;
  product_description: string | null;
  created_by: number;
  woocommerce_product_id: number | null;
  woocommerce_disable_sync: number;
  preparation_time_in_minutes: number | null;
  warranty_id: number | null;
  is_inactive: number;
  not_for_selling: number;
  selling_price: number | null;
  purchase_price: number | null;
  image_url: string;
  product_variations: ProductVariation[];
  brand: string | null;
  unit: Unit;
  category: Category;
  sub_category: string | null;
  product_tax: string | null;
  product_locations: ProductLocation[];
};

type ProductVariation = {
  id: number;
  variation_template_id: number | null;
  name: string;
  product_id: number;
  is_dummy: number;
  created_at: string;
  updated_at: string;
  variations: Variation[];
};

type Variation = {
  id: number;
  name: string;
  product_id: number;
  sub_sku: string;
  product_variation_id: number;
  woocommerce_variation_id: number | null;
  variation_value_id: number | null;
  default_purchase_price: string;
  dpp_inc_tax: string;
  profit_percent: string;
  default_sell_price: string;
  sell_price_inc_tax: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  combo_variations: any[];
  variation_location_details: VariationLocationDetail[];
  media: any[];
  discounts: any[];
};

type VariationLocationDetail = {
  id: number;
  product_id: number;
  product_variation_id: number;
  variation_id: number;
  location_id: number;
  qty_available: string;
  created_at: string;
  updated_at: string;
};

type Unit = {
  id: number;
  business_id: number;
  actual_name: string;
  short_name: string;
  allow_decimal: number;
  base_unit_id: number | null;
  base_unit_multiplier: number | null;
  created_by: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};

type Category = {
  id: number;
  name: string;
  business_id: number;
  short_code: string | null;
  parent_id: number;
  created_by: number;
  woocommerce_cat_id: number | null;
  category_type: string;
  description: string | null;
  slug: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};

type ProductLocation = {
  id: number;
  business_id: number;
  location_id: string;
  name: string;
  landmark: string;
  country: string;
  state: string;
  city: string;
  zip_code: string;
  invoice_scheme_id: number;
  sale_invoice_scheme_id: number;
  invoice_layout_id: number;
  sale_invoice_layout_id: number;
  selling_price_group_id: number | null;
  print_receipt_on_invoice: number;
  receipt_printer_type: string;
  printer_id: number | null;
  mobile: string;
  alternate_number: string;
  email: string;
  website: string;
  featured_products: any;
  is_active: number;
  default_payment_accounts: string;
  custom_field1: string | null;
  custom_field2: string | null;
  custom_field3: string | null;
  custom_field4: string | null;
  accounting_default_map: any;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  pivot: {
    product_id: number;
    location_id: number;
  };
};
