export type BusinessLocation = {
  id: number;
  business_id: number;
  location_id: string;
  name: string;
  landmark: string;
  country: string;
  state: string;
  city: string;
  zip_code: string;
  invoice_scheme_id: number | null;
  sale_invoice_scheme_id: number;
  invoice_layout_id: number | null;
  sale_invoice_layout_id: number | null;
  selling_price_group_id: number | null | any;
  print_receipt_on_invoice: number | null;
  receipt_printer_type: string;
  printer_id: number | null;
  mobile: string;
  alternate_number: string;
  email: string;
  website: string;
  featured_products: any;
  is_active: number | boolean;
  custom_field1: string | null;
  custom_field2: string | null;
  custom_field3: string | null;
  custom_field4: string | null;
  accounting_default_map: any;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  payment_methods: {
    name: string;
    label: string;
    account_id: number | null;
  }[];
};

export type Product = {
  id: number;
  name: string;
  business_id: number;
  type: string;
  secondary_unit_id: number | null;
  sub_unit_ids: number[] | null;
  enable_stock: number;
  alert_quantity: string;
  sku: string;
  barcode_type: string;
  expiry_period: number | null;
  expiry_period_type: string | null;
  expiry_date: string;
  enable_sr_no: number;
  weight: number | null;
  product_custom_field1: string;
  product_custom_field2: string;
  product_custom_field3: string;
  product_custom_field4: string;
  product_custom_field5: string;
  product_custom_field6: string;
  product_custom_field7: string;
  product_custom_field8: string;
  product_custom_field9: string;
  product_custom_field10: string;
  product_custom_field11: string;
  product_custom_field12: string;
  product_custom_field13: string;
  product_custom_field14: string;
  product_custom_field15: string;
  product_custom_field16: string;
  product_custom_field17: string;
  product_custom_field18: string;
  product_custom_field19: string;
  product_custom_field20: string;
  image: string;
  woocommerce_media_id: number | null;
  product_description: string | null;
  created_by: number;
  woocommerce_product_id: number | null;
  woocommerce_disable_sync: number;
  preparation_time_in_minutes: number | null;
  warranty_id: number | null;
  is_inactive: number;
  not_for_selling: number;
  selling_price: number | null;
  purchase_price: number | null;
  image_url: string;
  product_variations: ProductVariation[];
  brand: string | null;
  unit: Unit;
  category: Category;
  sub_category: string | null;
  product_tax: string | null;
  product_locations: ProductLocation[];
};

type ProductVariation = {
  id: number;
  variation_template_id: number | null;
  name: string;
  product_id: number;
  is_dummy: number;
  created_at: string;
  updated_at: string;
  variations: Variation[];
};

type Variation = {
  id: number;
  name: string;
  product_id: number;
  sub_sku: string;
  product_variation_id: number;
  woocommerce_variation_id: number | null;
  variation_value_id: number | null;
  default_purchase_price: string;
  dpp_inc_tax: string;
  profit_percent: string;
  default_sell_price: string;
  sell_price_inc_tax: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  combo_variations: any[];
  variation_location_details: VariationLocationDetail[];
  media: any[];
  discounts: any[];
};

type VariationLocationDetail = {
  id: number;
  product_id: number;
  product_variation_id: number;
  variation_id: number;
  location_id: number;
  qty_available: string;
  created_at: string;
  updated_at: string;
};

type Unit = {
  id: number;
  business_id: number;
  actual_name: string;
  short_name: string;
  allow_decimal: number;
  base_unit_id: number | null;
  base_unit_multiplier: number | null;
  created_by: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};

type Category = {
  id: number;
  name: string;
  business_id: number;
  short_code: string | null;
  parent_id: number;
  created_by: number;
  woocommerce_cat_id: number | null;
  category_type: string;
  description: string | null;
  slug: string | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
};

type Media = {
  id: number;
  business_id: number;
  file_name: string;
  description: string | null;
  uploaded_by: number;
  model_type: string;
  woocommerce_media_id: string | null;
  model_media_type: string | null;
  model_id: number;
  created_at: string;
  updated_at: string;
  display_name: string;
  display_url: string;
};

type CreatedBy = {
  id: number;
  user_type: string | null;
  surname: string | null;
  first_name: string | null;
  last_name: string | null;
  username: string;
  email: string;
  language: string;
  contact_no: string | number | null;
  address: string | null;
  business_id: 3;
  available_at: string | null;
  paused_at: string | null;
  max_sales_discount_percent: string | null;
  allow_login: 1;
  status: "active";
  is_enable_service_staff_pin: 0;
  service_staff_pin: string | number | null;
  crm_contact_id: number | null;
  is_cmmsn_agnt: number;
  cmmsn_percent: string;
  selected_contacts: number;
  dob: string | null;
  gender: string | null;
  marital_status: string | null;
  blood_group: string | null;
  contact_number: string | number | null;
  alt_number: string | number | null;
  family_number: string | number | null;
  fb_link: string | null;
  twitter_link: string | null;
  social_media_1: string | null;
  social_media_2: string | null;
  permanent_address: string | null;
  current_address: string | null;
  guardian_name: string | null;
  custom_field_1: string | null;
  custom_field_2: string | null;
  custom_field_3: string | null;
  custom_field_4: string | null;
  bank_details: string;
  id_proof_name: string | null;
  id_proof_number: string | number | null;
  uuid: string;
  image_url: string;
  media: Media;
};

export type Items = {
  id: number;
  prev_quantity: number;
  current_quantity: number;
  stock_difference: number;
  product: Product;
  created_at: string;
  updated_at: string;
};

type ProductLocation = {
  id: number;
  business_id: number;
  location_id: string;
  name: string;
  landmark: string;
  country: string;
  state: string;
  city: string;
  zip_code: string;
  invoice_scheme_id: number;
  sale_invoice_scheme_id: number;
  invoice_layout_id: number;
  sale_invoice_layout_id: number;
  selling_price_group_id: number | null;
  print_receipt_on_invoice: number;
  receipt_printer_type: string;
  printer_id: number | null;
  mobile: string;
  alternate_number: string;
  email: string;
  website: string;
  featured_products: any;
  is_active: number;
  default_payment_accounts: string;
  custom_field1: string | null;
  custom_field2: string | null;
  custom_field3: string | null;
  custom_field4: string | null;
  accounting_default_map: any;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  pivot: {
    product_id: number;
    location_id: number;
  };
};

export type GetStockTakingResponse = {
  id: number;
  adjustment_type: string;
  ref_no: string;
  date_taken: string;
  created_at: string;
  updated_at: string;
  created_by: CreatedBy;
  location: BusinessLocation;
  items: Items[];
};

export type GetUserProfileResponse = {
  id: number;
  user_type: string;
  surname: string | null;
  first_name: string;
  last_name: string | null;
  username: string;
  email: string;
  language: string;
  contact_no: string | number | null;
  address: string | null;
  business_id: number;
  available_at: string | null;
  paused_at: string | null;
  max_sales_discount_percent: string | number | null;
  allow_login: number;
  status: string;
  is_enable_service_staff_pin: number;
  service_staff_pin: string | number | null;
  crm_contact_id: string | number | null;
  is_cmmsn_agnt: number;
  cmmsn_percent: string;
  selected_contacts: number;
  dob: string | null;
  gender: string | null;
  marital_status: string | null;
  blood_group: string | null;
  contact_number: string | number | null;
  alt_number: string | number | null;
  family_number: string | number | null;
  fb_link: string | null;
  twitter_link: string | null;
  social_media_1: string | null;
  social_media_2: string | null;
  permanent_address: string | null;
  current_address: string | null;
  guardian_name: string | null;
  custom_field_1: string | null;
  custom_field_2: string | null;
  custom_field_3: string | null;
  custom_field_4: string | null;
  bank_details: string;
  id_proof_name: string | null;
  id_proof_number: string | number | null;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
  uuid: string;
  is_admin: boolean;
  image_url: string;
  business: {
    id: number;
    name: string;
    currency_id: number;
    start_date: string;
    tax_number_1: string;
    tax_label_1: string;
    tax_number_2: string | null;
    tax_label_2: string | null;
    code_label_1: string | null;
    code_1: string | null;
    code_label_2: string | null;
    code_2: string | null;
    default_sales_tax: string | null;
    default_profit_percent: number;
    owner_id: number;
    time_zone: string;
    fy_start_month: number;
    accounting_method: string;
    default_sales_discount: string;
    sell_price_tax: string;
    logo: string | null;
    sku_prefix: string | null;
    enable_product_expiry: number;
    expiry_type: string;
    on_product_expiry: string;
    stop_selling_before: number;
    enable_tooltip: number;
    purchase_in_diff_currency: number;
    purchase_currency_id: number | null;
    p_exchange_rate: string;
    transaction_edit_days: number;
    stock_expiry_alert_days: number;
    keyboard_shortcuts: string;
    pos_settings: string;
    woocommerce_skipped_orders: string | null;
    woocommerce_wh_oc_secret: string | null;
    woocommerce_wh_ou_secret: string | null;
    woocommerce_wh_od_secret: string | null;
    woocommerce_wh_or_secret: string | null;
    pharmacyng_key: string | null;
    weighing_scale_setting: {
      label_prefix: string | null;
      product_sku_length: string;
      qty_length: string;
      qty_length_decimal: string;
    };
    enable_brand: number;
    enable_category: number;
    enable_sub_category: number;
    enable_price_tax: number;
    enable_purchase_status: number;
    enable_lot_number: number;
    default_unit: string | null;
    enable_sub_units: number;
    enable_racks: number;
    enable_row: number;
    enable_position: number;
    enable_editing_product_from_purchase: number;
    sales_cmsn_agnt: string | null;
    item_addition_method: number;
    enable_inline_tax: number;
    currency_symbol_placement: string;
    enabled_modules: string[];
    date_format: string;
    time_format: string;
    currency_precision: number;
    quantity_precision: number;
    ref_no_prefixes: {
      purchase: string;
      purchase_return: string | null;
      purchase_requisition: string | null;
      purchase_order: string | null;
      stock_transfer: string;
      stock_adjustment: string;
      sell_return: string;
      expense: string;
      contacts: string;
      purchase_payment: string;
      sell_payment: string;
      expense_payment: string | null;
      business_location: string;
      username: string | null;
      subscription: string | null;
      draft: string | null;
      sales_order: string | null;
    };
    theme_color: string;
    created_by: string | null;
    accounting_settings: string | null;
    enable_rp: number;
    rp_name: string | null;
    amount_for_unit_rp: string;
    min_order_total_for_rp: string;
    max_rp_per_order: string | null;
    redeem_amount_per_unit_rp: string;
    min_order_total_for_redeem: string;
    min_redeem_point: string | null;
    max_redeem_point: string | null;
    rp_expiry_period: string | null;
    rp_expiry_type: string;
    email_settings: {
      mail_driver: string;
      mail_host: string | null;
      mail_port: string | null;
      mail_username: string | null;
      mail_password: string | null;
      mail_encryption: string | null;
      mail_from_address: string | null;
      mail_from_name: string | null;
    };
    sms_settings: {
      sms_service: string;
      nexmo_key: string | null;
      nexmo_secret: string | null;
      nexmo_from: string | null;
      twilio_sid: string | null;
      twilio_token: string | null;
      twilio_from: string | null;
      url: string | null;
      send_to_param_name: string;
      msg_param_name: string;
      request_method: string;
      header_1: string | null;
      header_val_1: string | null;
      header_2: string | null;
      header_val_2: string | null;
      header_3: string | null;
      header_val_3: string | null;
      param_1: string | null;
      param_val_1: string | null;
      param_2: string | null;
      param_val_2: string | null;
      param_3: string | null;
      param_val_3: string | null;
      param_4: string | null;
      param_val_4: string | null;
      param_5: string | null;
      param_val_5: string | null;
      param_6: string | null;
      param_val_6: string | null;
      param_7: string | null;
      param_val_7: string | null;
      param_8: string | null;
      param_val_8: string | null;
      param_9: string | null;
      param_val_9: string | null;
      param_10: string | null;
      param_val_10: string | null;
    };
    custom_labels: string;
    common_settings: {
      default_credit_limit: string | null;
      default_datatable_page_entries: string;
    };
    is_active: number;
    created_at: string;
    updated_at: string;
    currency: {
      id: number;
      country: string;
      currency: string;
      code: string;
      symbol: string;
      thousand_separator: string;
      decimal_separator: string;
      created_at: string | null;
      updated_at: string | null;
    };
    logo_url: string;
    logo_path: string | null;
  };
  media: Media;
};
